version: '3.1'

volumes:
  collector-data:
  collector-data4:
  mongo-configdb:
  mongo-data:
  notebook-data:
  notebook-data4:
  notebook-tmp:
  ssh-keys:
  ssh-rsync-keys:
  viewer-data:

services:

#   manager:
#     image: 'jeremydouglass/we1s-manager:dockerhub'
#     entrypoint: tail -f /dev/null
#     # entrypoint: >
#     #   sh -c "python /we1s-wms/run.py &&
#     #          tail -f /dev/null
#     links:
#       - 'mongo'
#     ports:
#       - '5000:5000'
#     volumes:
#       - notebook-data4:/instance/workspace/
#       - collector-data4:/instance/tasks

  mongo:
    image: 'mongo'
    volumes:
      - mongo-configdb:/data/configdb
      - mongo-data:/data/db
      - collector-data4:/data
      - notebook-data4:/write

  mongo-express:
    image: 'mongo-express'
    links:
      - 'mongo'
    ports:
      - '8081:8081'
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
    - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}

#   rsync-server:
#     image: 'axiom/rsync-server'
#     ports:
#       - '8001:873' # rsyncd port
#       - '9001:22'  # sshd port
#     environment:
#       - USERNAME='jovyan'
#       - PASSWORD=${JUPYTER_PASSWORD}
#       - VOLUME='/data' # path for rsync. default: /data
#       - ALLOW=${RSYNC_ALLOW_IP} # space separated list of allowed sources. default: 192.168.0.0/16 172.16.0.0/12
#     volumes:
#       - collector-data4:/data
#       - notebook-data4:/write
#       - mongo-data:/mongo/data
#       - viewer-data:/view:z
#       - ssh-rsync-keys:/root/.ssh

  viewer:
    image: nginx
    # ports:
    #   - '10001:80'
    volumes:
      - notebook-data4:/usr/share/nginx/html:ro

  viewerauth:
    image: 'beevelop/nginx-basic-auth'
    ports:
      - '10001:80'
    environment:
      - PORT=80
      - FORWARD_HOST=viewer
      - FORWARD_PORT=80
      ## escape $ with $$ in Docker yml due to variable expansion
      ## example user/pass generated with htpasswd is foo:bar
      - HTPASSWD=${NGINX_BASICAUTH_HTPASSWD}

  viewer2:
    image: jeremydouglass/we1s-notebook-viewer:latest
    ports:
      - '10002:80'
    volumes:
      - viewer-data:/usr/share/nginx/html:ro

  workspacedev:
    image: 'jeremydouglass/preprocessing:clean'
    links:
      - 'mongo'
    user: 'root'
    # user: '1000:100'
    ports:
      - '11111:8888'
    volumes:
      - notebook-data4:/home/jovyan/write
#       - collector-data4:/home/jovyan/data
      - viewer-data:/home/jovyan/view:z
      - notebook-tmp:/tmp
      # note that in the newer labs notebook
      # these are parallel to ~/work, not under it
    environment:
      - GRANT_SUDO=${JUPYTER_GRANT_SUDO}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PASSWORD=${JUPYTER_PASSWORD}

# secrets:
#   ln_environment:
#     external: true
#   ln_password:
#     external: true
#   ln_project_id:
#     external: true
#   ln_username:
#     external: true
