version: '3.1'

volumes:
  collector-data:
  collector-data4:
  manager-db-data:
  mongo-data:
  notebook-data:
  notebook-data4:
  viewer-data:

services:
  collector:
    image: 'jeremydouglass/we1s-collector:latest'
    links:
      - 'mongo'
    volumes:
      - collector-data4:/data
      - notebook-data4:/write
      - viewer-data:/view:z
    secrets:
      - ln_environment
      - ln_password
      - ln_project_id
      - ln_username

  manager:
    # image: 'jeremydouglass/we1s-manager'
    image: 'jeremydouglass/we1s-manager:dockerhub'
    links:
      - 'mongo'
    ports:
      - '5000:5000'
    volumes:
      - notebook-data4:/instance/workspace/
      - collector-data4:/instance/tasks

  # manager-proxy:
  #   image: 'beevelop/nginx-basic-auth'
  #   links:
  #     - 'manager'
  #   ports:
  #     - '5000:80'
  #   environment:
  #     - PORT=80
  #     - FORWARD_HOST=manager
  #     - FORWARD_PORT=5000
  #     # generate htpasswd -- change $ to $$ for docker YML expansion escaping
  #     - HTPASSWD=scottkleinman:$$apr1$$4Gu6vafl$$5y8QuCYwHo5pxHsQoeL26/

  mongo:
    image: 'mongo'
    ##HAS A DIFFERENT MOUNT POINT FOR VOLUME--NOT SWAPPABLE
    # image: 'bitnami/mongodb:latest'
    ##DONT NEED PORTS UNTIL REPLACING LINKS AND USING NETWORKS
    # ports:
    #   - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - collector-data4:/data
      - notebook-data4:/write
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME
    #   - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: 'mongo-express'
    links:
      - 'mongo'
    ports:
      - '8081:8081'
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
    - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    # - ME_CONFIG_MONGODB_ADMINUSERNAME
    # - ME_CONFIG_MONGODB_ADMINPASSWORD

  viewer:
    image: nginx
    ports:
      - '10001:80'
    volumes:
      - notebook-data4:/usr/share/nginx/html:ro

  viewer2:
    image: jeremydouglass/we1s-notebook-viewer:latest
    ports:
      - '10002:80'
    volumes:
      - viewer-data:/usr/share/nginx/html:ro

  workspace:
    # image: 'jeremydouglass/we1s:dfrb'
    image: 'we1sdfrb20180730'
    ports:
      - '9999:8888'
    volumes:
      - notebook-data4:/home/jovyan/work/write
      - collector-data4:/home/jovyan/work/data
      - viewer-data:/home/jovyan/work/view:z
    environment:
      - GRANT_SUDO=${JUPYTER_GRANT_SUDO}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PASSWORD=${JUPYTER_PASSWORD}

  workspace2:
    image: 'jeremydouglass/we1snotebooks'
    user: '1000:100'
    ports:
      - '10000:8888'
    volumes:
      - notebook-data4:/home/jovyan/write
      - collector-data4:/home/jovyan/data
      - viewer-data:/home/jovyan/view:z
      # note that in the newer labs notebook
      # these are parallel to ~/work, not under it
    environment:
      - GRANT_SUDO=${JUPYTER_GRANT_SUDO}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PASSWORD=${JUPYTER_PASSWORD}

secrets:
  ln_environment:
    external: true
  ln_password:
    external: true
  ln_project_id:
    external: true
  ln_username:
    external: true
