version: '3.1'

volumes:
  collector-data:
  collector-data4:
  mongo-data:
  notebook-data:
  notebook-data4:
  ssh-keys:
  viewer-data:

services:
  collector:
    image: 'jeremydouglass/we1s-collector:latest'
    links:
      - 'mongo'
    volumes:
      - collector-data4:/data
      - notebook-data4:/write
      - viewer-data:/view:z
    secrets:
      - ln_environment
      - ln_password
      - ln_project_id
      - ln_username

  manager:
    image: 'jeremydouglass/we1s-manager:dockerhub'
    links:
      - 'mongo'
    ports:
      - '5000:5000'
    volumes:
      - notebook-data4:/instance/workspace/
      - collector-data4:/instance/tasks

  mongo:
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
      - collector-data4:/data
      - notebook-data4:/write

  mongo-express:
    image: 'mongo-express'
    links:
      - 'mongo'
    ports:
      - '8081:8081'
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
    - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}

 sshd:
   image: 'panubo/sshd'
   ports:
     - '10101:22'
   volumes:
     - collector-data4:/data
     - notebook-data4:/write
     - viewer-data:/view:z
     - mongo-data:/mongo/data
     - ssh-keys:/etc/ssh/keys
   environment:
     - SSH_USERS=${SSHD_SSH_USERS}  # list of user accounts and uids/gids to create. eg SSH_USERS=www:48:48,admin:1000:1000
     # - MOTD=${SSHD_MOTD}  # change the login message
     - SFTP_MODE=${SSHD_SFTP_MODE}  # if "true" sshd will only accept sftp connections
     - SFTP_CHROOT=${SSHD_SFTP_CHROOT}  # if in sftp only mode sftp will be chrooted to this directory. Default "/data"

  viewer:
    image: nginx
    ports:
      - '10001:80'
    volumes:
      - notebook-data4:/usr/share/nginx/html:ro

  viewer2:
    image: jeremydouglass/we1s-notebook-viewer:latest
    ports:
      - '10002:80'
    volumes:
      - viewer-data:/usr/share/nginx/html:ro

  workspace:
    image: 'we1sdfrb20180730'
    ports:
      - '9999:8888'
    volumes:
      - notebook-data4:/home/jovyan/work/write
      - collector-data4:/home/jovyan/work/data
      - viewer-data:/home/jovyan/work/view:z
    environment:
      - GRANT_SUDO=${JUPYTER_GRANT_SUDO}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PASSWORD=${JUPYTER_PASSWORD}

  workspace2:
    image: 'jeremydouglass/we1snotebooks:180808C'
    user: 'root'
    ports:
      - '10000:8888'
    volumes:
      - notebook-data4:/home/jovyan/write
      - collector-data4:/home/jovyan/data
      - viewer-data:/home/jovyan/view:z
      # note that in the newer labs notebook
      # these are parallel to ~/work, not under it
    environment:
      - GRANT_SUDO=${JUPYTER_GRANT_SUDO}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PASSWORD=${JUPYTER_PASSWORD}

secrets:
  ln_environment:
    external: true
  ln_password:
    external: true
  ln_project_id:
    external: true
  ln_username:
    external: true
